find action yml bugs

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -48,13 +48,16 @@ jobs:
         with:
           python-version: '3.11' # Specify your desired Python version
 
-      - name: Install Python build dependencies and build wheel
-        id: build_the_wheel
-        run: |
+      - name: check code path
+        run: 
+          ls -l astroquery_cli || (echo "astroquery_cli code error that is no code！" && exit 1)
+          [ -f astroquery_cli/__init__.py ] || (echo "astroquery_cli 缺 __init__.py" && exit 1)
+
+      - name: Build wheel
+        run: 
           python -m pip install --upgrade pip build
-          ls -l "${PY_SITE_PACKAGES}/astroquery_cli"
           python -m build --wheel
-          # Find the generated wheel file (assuming one py3-none-any wheel)
+          unzip -l dist/*.whl
           BUILT_WHEEL_FILE=$(ls dist/*-py3-none-any.whl 2>/dev/null | head -n 1)
           if [[ -z "$BUILT_WHEEL_FILE" ]]; then
             echo "Error: No wheel file found in dist/ matching pattern *-py3-none-any.whl"
